### ISSUE TITLE
Unable to copy/paste from rendered PDF text within the paper page

### ISSUE THREAD

**Issue by joycesticks** [ResearchHub/discussion#48] opened 2021-05-18 16:54 UTC
Occasionally I have tried to copy/paste text from the rendered PDF in order to look up terms or make notes. 

For some reason, the text is unable to be copied and pasted. Would it be difficult to fix this?

**Comment by thomas-vu** [comment] 2021-05-19 02:57
I can't seem to reproduce this, could you provide more details?

**Comment by lightninglu10** [comment] 2021-05-19 02:58
Also can't reproduce here.

**Comment by lightninglu10** [comment] 2021-05-19 02:59
Okay, I can reproduce -- it's when you're logged out.

**Comment by lightninglu10** [comment] 2021-05-19 03:25
@thomas-vu I'm about to push a fix for this

**Comment by thomas-vu** [comment] 2021-05-19 03:26
Nice!

**Closed** 2021-05-19 03:31 UTC
Labels: bug
